### ISSUE TITLE
High DPI devices calling toSVG has the width/height cut off

### ISSUE THREAD

**Issue by manstie** [szimek/signature_pad#753] opened 2024-01-16 07:51 UTC
**Do you want to request a feature or report a bug?**

Bug

**What is the current behavior?**

When calling `toDataURL('image/svg+xml', { includeBackgroundColor: false });` or `toSVG({ includeBackgroundColor: false });` on a high DPI device (e.g. latest phones), the SVG viewBox/width/height output is not the true size of the dimensions of the input.

The input canvas:
![screenshot](https://github.com/szimek/signature_pad/assets/12475567/60d754d1-9cbd-46b7-b566-33e43c975535)

The output svg:
![svg](https://github.com/szimek/signature_pad/assets/12475567/5a996ad7-a69a-4f51-90ac-6f5a8f61b51b)

**What is the expected behavior?**

The output png:
![png](https://github.com/szimek/signature_pad/assets/12475567/61388a61-c0f7-4e29-98f4-9fbf1afcff36)

This, but an SVG.

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**

Windows 10
Google Chrome 120.0.6099.216 (Dev tools - iPhone 14 Pro Max)
signature_pad 4.1.7

**Comment by UziTech** [comment] 2024-01-16 08:45
duplicate of #675 

see https://github.com/szimek/signature_pad#handling-high-dpi-screens

**Closed by UziTech** 2024-01-16 08:45 UTC

**Comment by manstie** [comment] 2024-01-16 09:17
You mention that the output of the PNG would be the wrong size without proper handling of DPI, yet this example shows the PNG is the right size?
