### ISSUE TITLE
Clearing issue with Android and Chrome

### ISSUE THREAD

**Issue by natebrunette** [szimek/signature_pad#116] opened 2015-09-10 00:31 UTC
I'm running into an issue when using this in a mobile Chrome browser on an android device running Android 5.1.1 and Chrome 45.0.2454.84.

After I sign, if I touch/drag the screen a couple times the signature disappears.  `isEmpty()` still returns false.  Is there a way around this issue?

**Comment by szimek** [comment] 2015-09-10 07:58
I don't have access to a device with Android 5.1.1, so it's a bit hard for me to reproduce. I'll try later today with Android 5.0.2. Could you check if you're getting any JS errors in dev tools console?

**Comment by breckenedge** [comment] 2015-09-10 13:21
I'm also experiencing this issue on iOS 8.4.1 Safari. I've connected to the developer console via USB and can confirm that there are no error messages on the console. There is, however, a resize event firing whenever I scroll aggressively or beyond the edge of the page. Will investigate further.

**Comment by szimek** [comment] 2015-09-10 13:26
If it's really caused by resize event and you're on mobile device (i.e. it's less likely that the screen size will change, though it's still possible), you might try to listen to orientation change event instead.

**Comment by breckenedge** [comment] 2015-09-10 13:28
Excellent advice, will try.

**Comment by natebrunette** [comment] 2015-09-10 13:30
@breckenedge I'm going to give this a shot when I have time.  I'd appreciate it if you could report back with what you find.  Thanks!

**Comment by breckenedge** [comment] 2015-09-10 13:39
Listening for "orientationchange" did not clear the signature field when scrolling, so it works! Note I've also upgraded to v1.5.0.

I was using jQuery's `resize()` when I should have used `orientationchange` to resize the canvas to the width of the parent element (among other things) when switching from portrait to canvas and back, so causes the canvas to clear when scrolling/dragging:

````javascript
$(document).resize(function () {
  $("#signature").attr("width", $("#signature").parent().width());
});
````

but this does

````javascript
window.addEventListener("orientationchange", function () {
  $("#signature").attr("width", $("#signature").parent().width());
}, false)
````

**Comment by szimek** [comment] 2015-11-06 22:22
Looks like the problem is solved, so I'm closing this issue. If there are still some problems, please reopen it.

**Closed by szimek** 2015-11-06 22:22 UTC
