### ISSUE TITLE
1.60 Not working on VueJS

### ISSUE THREAD

**Issue by edwinnnss** [szimek/signature_pad#236] opened 2017-03-29 08:53 UTC
at 1.5.3 signature-pad working on vuejs, but after update to 1.60 not working,
any help ?

**Comment by szimek** [comment] 2017-03-29 08:56
Do you get any errors or can provide a repo or jsfiddle/jsbin/something to reproduce it?

**Comment by mkarnicki** [comment] 2017-03-29 08:56
Appreciate this bug report. If possible, provide a minimal example that shows signature-pad doesn't work with Vue. Saying "it doesn't work with Vue" is like "It doesn't work with React" - there's a lot of things that could have gone wrong :).

**Comment by janl** [comment] 2017-03-29 10:21
Heya, signature_pad stopped working for us as well and it’s because `signature_pad.min.js` now lives in `dist/` instead of the top level module directory. `package.json` now points to the right file on disk, but we were using the file location in our build task. The fix is easy, and if there is a way to make gulp/[gulp-useref](https://www.npmjs.org/package/gulp-useref/) use `package.json` entry points instead of file paths, we’d love to hear about it, but that’s obviously out of scope for this ticket.

I’m commenting because I think it might have warranted doing a breaking 2.0.0 release for this. cc @espy.

**Comment by szimek** [comment] 2017-03-31 08:13
@janl Hey, you're right. I thought that adding correct path in package.json would be enough and it's mentioned in changelog as well, but I guess it's not enough. I also stopped supporting Bower, so it might be better to release it as 2.0 anyway. I'll do it this weekend.

**Comment by szimek** [comment] 2017-03-31 08:35
I've just re-released 1.6.0 as 2.0.0.

**Comment by janl** [comment] 2017-03-31 16:54
Cool, thanks!

**Closed** 2017-04-08 19:09 UTC
Labels: bug
