### ISSUE TITLE
onBegin should fire before everything else

### ISSUE THREAD

**Issue by pxwee5** [szimek/signature_pad#548] opened 2021-07-02 01:31 UTC
**Do you want to request a feature or report a bug?**
Bug that enables the feature where we can clear the signature pad whenever we make a signature.

**What is the current behavior?**
If I do `SignaturePad.clear()` in `onBegin` now, I will get an error.

**What is the expected behavior?**
Should not error if I do the above.

**Solution**
Move the onBegin call to the top, before everything else.
```
SignaturePad.prototype._strokeBegin = function (event) {
  if (typeof this.onBegin === 'function') {
    this.onBegin(event);
  }

  this._data.push([]);
  this._reset();
  this._strokeUpdate(event);
};
```
@szimek do you think this will break anything that was intended for this callback ?

Another non-breaking solution would be to add a `beforeBegin()` prop to handle this callback.

**Comment by UziTech** [comment] 2021-07-02 02:57
duplicate of #378

**Closed** 2021-07-02 03:07 UTC
