### ISSUE TITLE
Signature not getting captured on Microsoft surface pro 4

### ISSUE THREAD

**Issue by ghost** [szimek/signature_pad#245] opened 2017-04-14 19:26 UTC
Hi,

I am using a stylus to enter my signature using app developed on Microsoft surface pro 4. I am not able to capture the signature from the same. It works if I don't use a stylus.

Current behavior:
User enters signature using stylus. Signature gets entered. However the base64 of the signature image is not obtained.

Expected behavior:

User enters signature using stylus. Signature gets entered. However the base64 of the signature image is obtained.

Version of signature pad : Latest
Target device : MS Surface pro 4

**Comment by szimek** [comment] 2017-04-16 17:29
Hi @karanbalkar I don't understand. Does it mean that when using a stylus nothing gets drawn or that `#toDataURL` doesn't return anything?

**Comment by Ben855** [comment] 2017-07-05 15:43
Starting 7/3/2017 the stylus stopped working (nothing gets drawn on screen).  It had worked previously.
Using finger it will display.
The devices are MS Surface pro 4
I upgraded to the latest version of signature pad without effect.

**Comment by szimek** [comment] 2017-07-05 15:57
@Ben855 Which browser are you using? Edge? Which version exactly? Looks like when you use stylus it uses some other events than mouse and touch events...

**Comment by Ben855** [comment] 2017-07-05 16:09
I am using Chrome browser

**Comment by Ben855** [comment] 2017-07-05 16:21
Did further testing It will draw in IE.
In Chrome, using the Demo it will work initially, 
      but then stops after doing clear, have to refresh to get it to write again. 
      I do have two canvases defined on the page.

**Comment by szimek** [comment] 2017-07-05 17:36
Unfortunately, I don't own MS Surface and it's not available on Browserstack, so it's hard for me to debug what's actually going on there...

**Comment by Ben855** [comment] 2017-07-05 18:51
I need to borrow 1 to be able to debug.  
Hopefully I can debug it in the next few days.

**Comment by Ben855** [comment] 2017-07-06 15:32
Using the Demo, it is calling mouse events the first time I draw.  After I remove the stylus from the canvas it does not receive mouse events anymore from the stylus ( I can't draw anything else with the stylus

**Comment by farshadsh** [comment] 2017-07-20 17:21
Same issue here, it was working before but now it does not, it's working with FireFox, Edge, even Google Canary but Google Chrome which is wired.

**Comment by onigunn** [comment] 2017-08-10 06:48
I can confirm this. Using the demo: Initially you are able to draw. After you move stylus from the screen and try to continue drawing nothing happens.

Chrome: 59.0.307
Surface 4 Pro with Stylus

**Comment by szimek** [comment] 2018-07-29 10:05
It's been a while, but I've just added support for pointer events in the latest beta (`3.0.0-beta.3`), so it would be great if anyone has access to a tablet with stylus and could try it out.

**Comment by szimek** [comment] 2018-08-19 20:48
I'm closing this issue. If it still doesn't work with the latest beta versions, please open a new issue.

**Closed by szimek** 2018-08-19 20:48 UTC
