### ISSUE TITLE
incorrect scaling/offset when using css zoom on a parent element (e.g. page)

### ISSUE THREAD

**Issue by koenhandekyn** [szimek/signature_pad#494] opened 2020-08-08 07:55 UTC
when using e.g. 'zoom: 1.5' as style on the main document (body/html/content/etc), the scaling and offset is corrupted and with the example resize snippet I'm not able to manage to compensate this as it results in both a corrupt offset and corrupt scale.

strangely, manual zooming in and out in the browser (ctrl-+ and ctrl--) does not result in corrupt behaviour after resize/refresh.

**Comment by pkeogan** [comment] 2020-10-10 00:22
Same issue, you ever find a fix?

**Comment by koenhandekyn** [comment] 2020-10-10 06:01
no unfortunately not - avoiding zoom at this time

**Comment by pkeogan** [comment] 2020-10-10 20:29
same, if i get a fix working ill let you know.

**Comment by samyabd** [comment] 2021-02-04 18:27
I have encountered the same issue. Did someone have found a fix ?

**Comment by koenhandekyn** [comment] 2021-02-04 19:33
so far I haven't

**Comment by UziTech** [comment] 2021-11-15 01:41
closing as stale

**Comment by mootari** [comment] 2022-03-30 21:53
The problem is that `_createPoint()` does not rescale the offset to the canvas dimensions. To fix it, apply the following monkeypatch to an instance:
```js
  const pad = new SignaturePad(canvas);
  // Get a reference to the Point class.
  const Point = pad._createPoint(0, 0, 0).constructor;
  // Replace the _createPoint method.
  pad._createPoint = function(x, y, pressure) {
    const rect = this.canvas.getBoundingClientRect();
    const sx = (x - rect.left) / rect.width * this.canvas.width;
    const sy = (y - rect.top) / rect.height * this.canvas.height;
    return new Point(sx, sy, pressure, new Date().getTime());
  };

**Comment by UziTech** [comment] 2022-03-31 00:49
@mootari can you create a PR with your patch?

**Comment by cyberbeat** [comment] 2022-10-17 12:23
Had the same problem. Above workaround did only work, when applied directly to the code. Please fix it with next official release. Why is this closed?

**Comment by UziTech** [comment] 2022-11-01 03:31
fixed in v4.1.2

**Comment by UziTech** [comment] 2022-11-08 06:30
unfixed in v4.1.4 seems there is an issue with dpr. I don't know if this is something that can be fixed. I can't find a way to tell what the zoom level is when it is set on a parent.

The problem is that `getBoundingClientRect()` gives the `top` and `left` as if there is no zoom. And, as far as I can tell, there is no way to determine the actual `top` and `left` of the canvas.

**Comment by marmooo** [comment] 2022-11-08 13:29
I think below code (zoom value) + #673 is the solution.
However, getComputedStyle() is slow, so I think it is better not to support by this solution.
It should be left to the user's implementation.
```
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      #foo { zoom: 0.75; }
      #canvas { width:100px; height:100px; border:1px solid #000; }
    </style> 
  </head>
  <body>
    <main class="container">
      <div style="zoom: 120%;">
        <div style="zoom: 3;">
          <div id="foo">
            <canvas id="canvas" width="100" height="100"></canvas>
          </div>
        </div>
      </div>
    </main>
    <script>
      const canvas = document.getElementById("canvas");
      let node = canvas;
      let zoom = parseFloat(getComputedStyle(canvas).zoom);
      while(node.parentNode instanceof Element) {
        node = node.parentNode;
        zoom *= parseFloat(getComputedStyle(node).zoom);
        console.log(getComputedStyle(node).zoom);
      }
      console.log(zoom);
    </script>
  </body>
</html>
```

**Closed** 2023-07-25 06:11 UTC
Labels: bug, wontfix

**Comment by alexandre-le-borgne** [comment] 2024-09-25 10:04
> The problem is that `_createPoint()` does not rescale the offset to the canvas dimensions. To fix it, apply the following monkeypatch to an instance:
> 
> ```js
>   const pad = new SignaturePad(canvas);
>   // Get a reference to the Point class.
>   const Point = pad._createPoint(0, 0, 0).constructor;
>   // Replace the _createPoint method.
>   pad._createPoint = function(x, y, pressure) {
>     const rect = this.canvas.getBoundingClientRect();
>     const sx = (x - rect.left) / rect.width * this.canvas.width;
>     const sy = (y - rect.top) / rect.height * this.canvas.height;
>     return new Point(sx, sy, pressure, new Date().getTime());
>   };
> ```

Works great!

I don't even need to use the onResize feature in the doc, which doesn't work at all (the drawing is just moved from the small version to the large version, keeping its size instead of getting bigger).
